#PATH to all data
data_dir: data

########## IMPORT DATA TO CONTENTFUL ##########

## EXPORTED XML FILE FROM WORDPRESS
wordpress_xml_path: /Users/owenhathaway/source/recipes_ihathaway/import/wordpress.xml

## CONVERT CONTENTFUL MODEL TO CONTENTFUL IMPORT STRUCTURE
content_model_json: /Users/owenhathaway/source/recipes_ihathaway/import/contentful_model.json
converted_model_dir: /Users/owenhathaway/source/recipes_ihathaway/import/contentful_structure.json

contentful_structure_dir: /Users/owenhathaway/source/recipes_ihathaway/import/default_contentful_structure.json

# contentful credentials
access_token: CFPAT-IF8AZ3sj81xbIAvsheqGlsPwHEOBU8gWXq8b6PEolbY
organization_id: 2yiwr5fCB27sW7i8C33txl
space_id: w1t1axzr981y
